language: go
go:
- 1.x
env: GO111MODULE=on
script:
- "./build/build ${TRAVIS_TAG}"
sudo: false
deploy:
  provider: releases
  api_key:
    secure: qktM/CtUT+Wwx/Yquyf4o7HkcttAf9ZQNH5Ybv4SFHk/f7B8Fpan0D5a5ixWXUeWNymlRbuJv+CGnyvvNfbiyE0pefvnUHKMuj6ywiSJeAdK9Wb53Idgu3WV43Cljgwdw+j7wkOugO/iQRvdDeOt/xGH3adfsGH/3UjytXhxWnrrDZCfJNnfUyUA442UQSSQRtDnK8s3YfA3U7VQSrjPuXodlu9TAjJ4TcwSv/WFyQNHBJD7TqNYvVzsn4vZ2KzaDRBvqINFVe87udgjvtNm6qYFjQ0vOzPwYkFfylvchrMzeuaH64CZFqHv/JP8Fxdg8HPHidguyRd5b0RNsc59Eo7ckrCDr9iSTye0Jz7csaGx30JTdY1ckyhji66J4jd+snxn8rmuWUdnfRj9j1Se3yTa7IdeYTgeo+2N36RhO6BhgRMJ8hfhE/83+HXN0UnhwQoS3H0tXAGqTOyAOrnLM9zDJhR0Ci1Xf2QvC4++h3DBcUL7yWGEoCQ1zjclWpeB8tSqlohefHDGXavVMX/IKbuqry4QQmBuJcdJDnhccY2HwhHULmKNorZ4F3wWVI2lkt1RaYZ8RJyMBIJs0OyxJ5iaHVP7ABJeX0Yr1C/Up43hmUIhM4Q9Pkhl5sQGsULFJ8IDAy1sHLAVlybWJdAB6VmVZCO5diQK/O6ecFJpQR0=
  file: "*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: Aestek/consul-timeline
    tags: true
